/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jdc.mtp;

import com.jdc.mtp.core.Execution;

import java.awt.*;

public class App {

    public static void main(String[] args) {
        EventQueue.invokeLater(()-> {
            try {
                new Execution();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        });
    }
}
